import { ThemeSpec } from "./ThemeSpec";

export const default_theme_spec: ThemeSpec = {
  "background_colour.body": "#ffffff",
  "foreground_colour.body": "#222222",
  "background_colour.feature": "#ffffff",
  "foreground_colour.feature": "#222222",
  "background_colour.highlight": "linear-gradient(240deg, #d0d0d0ff 0%, #c0c0c0ff 50%, #dbdbdbff 100%)",
  "foreground_colour.highlight": "#333333",
  "background_colour.contrast": "linear-gradient(163deg, #16dfb7ff 0%, #73F0A7 50%, #65ED53 100%)",
  "foreground_colour.contrast": "#222222",
  "background_colour.error": "linear-gradient(163deg, #df1616ff 0%, #f07373ff 50%, #ed5372ff 100%)",
  "foreground_colour.error": "#222222",

  "breakpoint_query.xs": "@container section (min-width: 0px)",
  "breakpoint_max_width.xs": "320px",
  "breakpoint_query.sm": "@container section (min-width: 420px)",
  "breakpoint_max_width.sm": "410px",
  "breakpoint_query.md": "@container section (min-width: 600px)",
  "breakpoint_max_width.md": "580px",
  "breakpoint_query.lg": "@container section (min-width: 1100px)",
  "breakpoint_max_width.lg": "1050px",
  "breakpoint_query.xl": "@container section (min-width: 1440px)",
  "breakpoint_max_width.xl": "1350px",

  "megamenu.height": "calc(100vh - 150px)",
  "overlay.opacity": "0.75",

  "z_index.header": "1",
  "z_index.modal": "2",

  "modal.width.sm": "300px",
  "modal.width.md": "600px",
  "modal.width.large": "900px",
  "modal.height.sm": "300px",
  "modal.height.md": "600px",
  "modal.height.large": "900px",

  padding: "1rem",
  "padding.small": "0.5rem",
  margin: "1rem",
  "margin.small": "0.5rem",
  "margin.small.body.x": "0.25rem",
  gap: "1rem",
  font_family: "sans-serif",
  text_decoration: "none",
  font_size: "1rem",
  "font_size.p": "1rem",
  "font_size.h1": "4rem",
  "font_size.h2": "3.5rem",
  "font_size.h3": "3rem",
  "font_size.h4": "2.5rem",
  "font_size.h5": "2rem",
  "font_size.h6": "1.5rem",
  "font_size.small": "0.75em",
  font_weight: "normal",
  "font_weight.heading": "bold",
  "margin.p.y": "1rem",
  "margin.h1.y": "1.5rem",
  "margin.h2.y": "1.5rem",
  "margin.h3.y": "1.5rem",
  "margin.h4.y": "1.5rem",
  "margin.h5.y": "1.5rem",
  "margin.h6.y": "1.5rem",
  "margin.span.y": "0",

  border_width: "1px",
  border_style: "solid",
  border_colour: ":$.foreground_colour.body",
  "border_colour.error": "#df1616ff",
  border_radius: "0.5rem",
  border_shadow: "0 0 10px 0 #22222217",
  "border_shadow.focus": "0 0 20px 0 #16dfb799",

  "animation_speed.fast": "100ms",
  "animation_speed.slow": "500ms",
};
