version: 40
jobs:
  - name: Build and Publish
    steps:
      - !CheckoutStep
        name: Checkout Code
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: SUCCESSFUL
        optional: false
      - !CommandStep
        name: Build and Publish
        runInContainer: true
        image: "@server@/toolkit/nscript:latest"
        interpreter: !DefaultInterpreter
          commands: |
            #! /bin/bash
            set -e
            set -v
            npm config set @@toolkit:registry https://git.paulandsophie.uk/toolkit/~npm/
            npm config set -- '//git.paulandsophie.uk/toolkit/~npm/:_authToken' "@job_token@:@secret:access-token@"

            npm install
            nscript components:build
        useTTY: true
        condition: SUCCESSFUL
        optional: false
        registryLogins:
          - registryUrl: "@server@"
            userName: "@job_token@"
            passwordSecret: access-token
    triggers:
      - !BranchUpdateTrigger
        branches: master
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 14400
